### ISSUE TITLE
作废

### ISSUE THREAD

**Issue by WanFengZ** [besafe2020june/TragicEvent#19]

**Comment by WanFengZ** [comment]
第一时间看到反馈给滴滴客服了，客服说已经有视频证据了，但是还是没有司机信息

**Comment by yyyyh0202** [comment]
我看过原po发的17分钟视频，后期是做了黑白处理的，你这个链接里的拼接的痕迹太重了，而且座椅颜色也不对，根本就是假的

**Comment by yyyyh0202** [comment]
> https://jjdong3.com/videos/11984/6-10/

我看过原po发的17分钟视频，后期是做了黑白处理的，你这个链接里的拼接的痕迹太重了，而且座椅颜色也不对，根本就是假的

**Comment by besafe2020june** [comment]
请自行删除这则违法材料，我怕你被抓。

**Comment by WanFengZ** [comment]
> > https://jjdong3.com/videos/11984/6-10/
> 
> 我看过原po发的17分钟视频，后期是做了黑白处理的，你这个链接里的拼接的痕迹太重了，而且座椅颜色也不对，根本就是假的

仔细对比了下，确实有拼接的可能
